/*
  Given an array containing numbers corresponding to keypad, find all possible words sorted lexicographically that can be generated by pressing these numbers.
*/

#include<iostream>
#include<vector>
#include<algorithm>
using namespace std;

string hash_list[10] = {"","","abc","def","ghi","jkl","mno","pqrs","tuv","wxyz"};

void possibleWordsUtil(int a[],int n, vector<string> &res, int ind=0, string curr="")
{
    if (ind == n)
    {
        res.push_back(curr);
        return;
    }
    string r = hash_list[a[ind]];
    for (int i=0;i<r.size();i++)
    {
        possibleWordsUtil(a, n, res, ind+1, curr+r[i]);
    }
}

vector <string> possibleWords(int a[], int N)
{
    vector <string> ans;
    possibleWordsUtil(a,N,ans);
    sort(ans.begin(),ans.end());
    return ans;
}

int main(int argc, char const *argv[])
{
    int n;
    cin>>n;
    int a[n];

    for(int i=0;i<n;i++)
    {
        cin>>a[i];
    }
    
    cout<<"Possible Words : \n";
    
    vector<string>res = possibleWords(a,n);
    for (int i=0;i<res.size();i++)
    {
        cout<<res[i]<<"  ";
    }
    cout<<endl;
    return 0;
}

